---
- name: Set default state_file
  ansible.builtin.set_fact:
    state_file: "{{ retrieve_state_source }}"

- name: Fetch state if remote
  when: "'http://' in retrieve_state_source or 'https://' in retrieve_state_source"
  block:
    - name: Fetch remote state
      ansible.builtin.get_url:
        url: "{{ retrieve_state_source }}"
        dest: /tmp/state.tf
      delegate_to: localhost

    - name: Override state_file
      ansible.builtin.set_fact:
        state_file: /tmp/state.tf

- name: Set terraform_state var
  ansible.builtin.set_fact:
    retrieve_state_result: "{{ lookup('file', state_file) | from_json }}"
