---
- name: Init var
  ansible.builtin.set_fact:
    tainted_servers: { }

- name: Save_servers
  ansible.builtin.include_tasks: save_server.yml
  loop: "{{ terraform_state.resources }}"
  loop_control:
    loop_var: resource
  when: resource.type == "openstack_compute_instance_v2"

- name: Read tfvars file
  ansible.builtin.set_fact:
    tfvars_content: "{{ lookup('file', tfvars_file)|from_json }}"

- name: Read named workers
  ansible.builtin.set_fact:
    named_workers: "{{ tfvars_content.named_workers }}"

- name: Include untaint tasks
  ansible.builtin.include_tasks: untaint.yml
  loop: "{{ tainted_servers | dict2items }}"

- name: Set new tfvars file
  ansible.builtin.template:
    src: empty.j2
    dest: "{{ tfvars_file }}"
  vars:
    content: "{{ tfvars_content | combine({'named_workers': named_workers}) | to_json }}"
