---
- name: Retrieve info for {{ item.value.name }}/{{ item.value.id }}
  openstack.cloud.server_info:
    server: "{{ item.value.id }}"
  ignore_errors: true
  register: server_info
  check_mode: false
  environment:
    OS_REGION_NAME: "{{ item.value.region }}"

- name: Untaint server {{ item.value.name }}/{{ item.value.id }}
  ansible.builtin.command:
    chdir: "{{ terraform_dir }}"
    cmd: terraform untaint {{ item.key | quote }}
  when:
    - server_info.servers | length
    - server_info.servers.0["vm_state"] in ["active", "building"]
    - server_info.servers.0["power_state"] in [0, 1]
  notify: Refresh terraform state

- name: Remove named server in error {{ item.value.name }}/{{ item.value.id }} from TFVARS
  when:
    - server_info.servers | length
    - server_info.servers.0["vm_state"] == "error"
    - item.value.name in named_workers
  ansible.builtin.set_fact:
    named_workers: "{{ named_workers | dict2items | rejectattr('key', 'equalto', item.value.name) | items2dict }}"
