# Managed by centralesupelec.mydocker.common: defer docker restart
$nrconf{override_rc}->{qr(^docker)} = 0;
$nrconf{override_rc}->{qr(^containerd)} = 0;
$nrconf{override_rc}->{qr(^thuv-docker)} = 0;
$nrconf{restart} = 'a';
