- name: Create app folder
  ansible.builtin.file:
    name: /opt/kaniko-executor
    state: directory

- name: Create Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: /opt/kaniko-executor/Dockerfile

- name: Create kaniko executor docker image
  community.docker.docker_image_build:
    name: kaniko-executor-my-docker
    path: /opt/kaniko-executor
