---
- name: Ensure caddy parent directory exists
  ansible.builtin.file:
    path: "{{ caddyfile_storage_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Caddyfile
  ansible.builtin.template:
    src: "templates/Caddyfile.j2"
    dest: "{{ caddyfile_storage_path }}"
    mode: 0644
    owner: root
    group: root

- name: Create caddy service
  docker_swarm_service:
    name: caddy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    replicas: 1
    labels:
      caddy_0: "(default_response)"
      caddy_0.respond: "410"
      caddy_1: "http://"
      caddy_1.import: "default_response"
      caddy_2: "https://"
      caddy_2.import: "default_response"
    publish:
      - published_port: 80
        target_port: 80
        mode: ingress
      - published_port: 443
        target_port: 443
        mode: ingress
    networks:
      - "{{ caddy_overlay_network }}"
    env:
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      - source: "{{ caddy_cert_file_source_path }}"
        target: "{{ caddy_cert_file_target_path }}"
        type: bind
        readonly: yes
      - source: "{{ caddy_key_file_source_path }}"
        target: "{{ caddy_key_file_target_path }}"
        type: bind
        readonly: yes
      - source: "{{ caddyfile_storage_path }}"
        target: "/etc/caddy/Caddyfile"
        type: bind
        readonly: yes
    placement:
      constraints:
        - node.role == manager
