---
- name: Create caddy overlay network if it doesn't exit
  docker_network:
    name: "{{ caddy_overlay_network }}"
    attachable: yes
    driver: overlay
    ipam_config:
      - gateway: "{{ caddy_overlay_network_subnet | ansible.utils.ipaddr('next_usable') }}"
        subnet: "{{ caddy_overlay_network_subnet }}"
