- name: Check if centralesupelec/mydockervolume plugin already installed
  ansible.builtin.command: docker plugin list
  register: plugin_list
  changed_when: false

- name: Install docker centralesupelec/mydockervolume plugin
  ansible.builtin.command: "docker plugin install {{ docker_swarm_volume_plugin }} --alias=centralesupelec/mydockervolume LOG_LEVEL=debug DRIVER_MODE=FS --grant-all-permissions"
  when: '"centralesupelec/mydockervolume" not in plugin_list.stdout'
