- name: Check if centralesupelec/mydockervolume plugin already installed
  ansible.builtin.command: "docker plugin inspect centralesupelec/mydockervolume -f '{{ '{{' }}.PluginReference{{ '}}' }}'"
  register: plugin_inspect
  changed_when: false
  ignore_errors: true

- name: Define if should upgrade plugin
  changed_when: false
  set_fact:
    docker_swarm_volume_upgrade_internal: true
  when: (plugin_inspect.rc == 0) and (docker_swarm_volume_plugin != (plugin_inspect.stdout|replace("docker.io/", ""))) and docker_swarm_volume_upgrade

- name: Remove old plugin
  ansible.builtin.command: docker plugin rm -f centralesupelec/mydockervolume
  when: docker_swarm_volume_upgrade_internal

- name: Install docker centralesupelec/mydockervolume plugin
  ansible.builtin.command: "docker plugin install {{ docker_swarm_volume_plugin }} --alias=centralesupelec/mydockervolume LOG_LEVEL=debug DRIVER_MODE=FS --grant-all-permissions"
  when: '("not found" in plugin_inspect.stderr) or docker_swarm_volume_upgrade_internal'
  register: output
  changed_when: '"Installed plugin" in output.stdout'
