---
- name: getent
  become: yes
  getent:
    database: passwd
    key: "{{ item }}"
    split: ":"

- name: set fact
  set_fact: 
    user_homes: "{{ user_homes | d({}) | combine({item: getent_passwd[item][4]}) }}"