---
- name: getent
  become: yes
  ansible.builtin.getent:
    database: passwd
    key: "{{ item }}"
    split: ":"

- name: set fact
  ansible.builtin.set_fact:
    user_homes: "{{ user_homes | d({}) | combine({item: getent_passwd[item][4]}) }}"
