---
- name: Configure apt list changes
  ansible.builtin.copy:
    src: listchanges.conf
    dest: '/etc/apt/listchanges.conf'
  become: true

- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  tags:
    - install
    - update

- name: Install basic utilities
  ansible.builtin.apt:
    name:
      - man
      - vim
      - htop
      - git
      - zsh
      - screen
      - mosh
      - locate
      - apt-listchanges
      - locales
      - rsync
      - ncdu
      - traceroute
      - ldnsutils
      - lsof
      - silversearcher-ag
      - ncurses-term
      - fail2ban
      - gnupg
      - curl
      - unzip
    autoclean: true
    state: present
  tags:
    - install
    - update
  become: true

- name: Set timezone to Europe/Paris
  community.general.timezone:
    name: Europe/Paris
  tags:
    - install
    - timezone
  notify: Restart rsyslog
  become: true

- name: Generate locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    - en_US.UTF-8
    - fr_FR.UTF-8
  tags:
    - install
  become: true

- name: Set shell to ZSH
  when: common_users is defined
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/zsh
  loop: "{{ common_users }}"
  tags:
    - install
    - zsh
  become: true

- name: Include homes configuration
  when: common_users is defined and (user_homes is undefined or item not in user_homes)
  ansible.builtin.include_tasks: homes.yml
  loop: "{{ common_users }}"

- name: ZSH configuration
  ansible.builtin.include_tasks: zsh.yml
  tags:
    - install
    - zsh

- name: Screen configuration for users
  when: common_users is defined
  ansible.builtin.copy:
    src: screenrc
    dest: "{{ user_homes[item] }}/.screenrc"
  tags:
    - install
    - screen
  loop: "{{ common_users }}"
  become: true

- name: Provision ssh keys
  when: (common_ssh_authorized_keys | default({}) | length > 0) and (item.value | default([]) | length > 0)
  ansible.posix.authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{item.value | join('\n') if item.value is defined and item.value is iterable else ''}}"
    exclusive: true
  loop: "{{ (common_ssh_authorized_keys | default({})) | dict2items }}"
  become: true
  tags:
    - ssh
...
