---
- name: Create tmp folder
  ansible.builtin.file:
    path: "{{ common_local_tmp_folder }}/oh-my-zsh"
    state: directory
  delegate_to: localhost
  run_once: true
  vars:
    ansible_become: false

- name: Clone oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ common_local_tmp_folder }}/oh-my-zsh"
    version: master
  delegate_to: localhost
  run_once: true
  vars:
    ansible_become: false
  tags:
    - install
    - zsh

- name: Clone oh-my-via
  ansible.builtin.git:
    repo: https://github.com/badouralix/oh-my-via
    dest: "{{ common_local_tmp_folder }}/oh-my-zsh/custom/themes/oh-my-via"
    version: master
  delegate_to: localhost
  run_once: true
  vars:
    ansible_become: false
  tags:
    - install
    - zsh

- name: Create oh-my-zsh installation folder
  ansible.builtin.file:
    path: /etc/zsh/.oh-my-zsh
    state: directory
  become: true

- name: Create oh-my-zsh tmp folder
  ansible.builtin.file:
    path: /tmp/oh-my-zsh/
    state: directory
    owner: "{{ ansible_user }}"
    recurse: true
  become: true

# rsync is much faster than copy but does not work with passwordfull sudo
- name: Copy oh-my-zsh to remote
  ansible.posix.synchronize:
    src: "{{ common_local_tmp_folder }}/oh-my-zsh/"
    dest: /tmp/oh-my-zsh
  tags:
    - copy
    - zsh
  become: false

- name: Copy oh-my-zsh from remote to the right place
  delegate_to: "{{ inventory_hostname }}"
  ansible.posix.synchronize:
    src: /tmp/oh-my-zsh/
    dest: /etc/zsh/.oh-my-zsh
    owner: false
    group: false
  tags:
    - copy
    - zsh
  become: true

- name: Ensure correct permissions
  ansible.builtin.file:
    path: /etc/zsh/.oh-my-zsh/
    recurse: true
    owner: root
    group: root
    mode: "g-w"
  become: true

- name: Copy zshrc
  ansible.builtin.copy:
    src: zshrc
    dest: /etc/zsh/zshrc
  tags:
    - install
    - update
    - zsh
  become: true

- name: Create an empty .zshrc
  when: common_users is defined
  ansible.builtin.copy:
    content: ""
    dest: "{{ user_homes[item] }}/.zshrc"
    force: false
  loop: "{{ common_users }}"
  become: true
...
