---
- name: Install common tools
  hosts: all
  roles:
  - centralesupelec.mydocker.common
  - role: Datadog.datadog
    when: enable_datadog | default(False)
  - centralesupelec.mydocker.monitoring
  become: yes
