---
- name: Install common tools
  hosts: all
  become: yes
  roles:
    - centralesupelec.mydocker.common
    - role: Datadog.datadog
      when: enable_datadog | default(False)

- name: Install docker
  hosts: docker_swarm_manager:docker_swarm_worker
  become: true
  roles:
    - role: "nickjj.docker"
      tags: [ "docker" ]

- name: Create and configure docker swarm
  hosts: docker_swarm_manager:docker_swarm_worker
  roles:
    - centralesupelec.mydocker.ceph_install
    - role: centralesupelec.mydocker.docker_swarm
      vars:
        docker_swarm_volume_backend: "{{ enable_ceph | ternary('rbd', 'fs') }}"
  become: yes

- name: Tweak monitoring
  hosts: all
  roles:
    - centralesupelec.mydocker.monitoring
  become: yes

- name: Install docker api
  hosts: docker_swarm_manager
  roles:
    - centralesupelec.mydocker.docker_api

- name: Install web server
  hosts: web
  roles:
    - centralesupelec.mydocker.web
