- name: Generate an inventory from Terraform state
  hosts: localhost
  roles:
    - centralesupelec.mydocker.retrieve_state
    - role: centralesupelec.mydocker.generate_inventory
      vars:
        terraform_state: "{{ retrieve_state_result }}"
