- name: Update apt
  hosts: docker_swarm_manager:docker_swarm_worker
  become: yes
  tasks:
    - name: Wait for lock to be released
      shell: while lsof /var/{{ item }}; do sleep 10; done;
      changed_when: false
      loop:
        - lib/dpkg/lock-frontend
        - lib/apt/lists/lock
        - cache/apt/archives/lock

    - name: Update apt
      apt:
        update_cache: "yes"
        cache_valid_time: 3600

- name: Update apt
  hosts: docker_swarm_manager:docker_swarm_worker
  become: yes
  tasks:
    - name: Wait for /var/lib/dpkg/lock-frontend to be released
      shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;
      changed_when: false

- name: Install NVIDIA driver
  hosts: docker_swarm_worker
  become: true
  roles:
    - role: gpu-pre-docker
      when: gpu_type is defined

- name: Install docker
  hosts: docker_swarm_manager:docker_swarm_worker
  become: true
  pre_tasks:
    - name: Register docker config for GPU
      when: gpu_type is defined
      set_fact:
        docker__daemon_json: "{{ gpu_pre_docker__daemon_json }}"
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
    # Install NVIDIA docker runtime after Docker to avoid installing docker-ce as a default APT dependency for the driver
    - role: gpu-post-docker
      when: gpu_type is defined

- name: Install ssh keys
  hosts: docker_swarm_worker:docker_swarm_manager
  tasks:
    - when: common_ssh_authorized_keys is defined
      name: Provision ssh keys
      authorized_key:
        user: "{{ item.key }}"
        state: present
        key: "{{item.value | join('\n') if item.value is defined and item.value is iterable else ''}}"
        exclusive: "yes"
      loop: "{{ (common_ssh_authorized_keys|default({}))|dict2items }}"
      tags:
        - ssh

- name: Create and configure docker swarm
  hosts: docker_swarm_manager:docker_swarm_worker
  roles:
    - ceph-install
    - docker-swarm
  become: yes

- name: Create and configure swap on workers
  hosts: docker_swarm_worker
  roles:
    - geerlingguy.swap
  become: yes
