- name: Create and configure docker swarm
  hosts: docker_swarm_manager:docker_swarm_worker
  roles:
    - role: centralesupelec.mydocker.assert_on_prem
      when: gpu_type is defined
    - role: centralesupelec.mydocker.docker_swarm
      vars:
        docker_swarm_volume_backend: "{{ enable_ceph | ternary('rbd', 'fs') }}"
  become: true
