- name: Update apt
  hosts: docker_swarm_manager:docker_swarm_worker
  become: true
  tasks:
    - name: Wait for lock to be released
      ansible.builtin.shell: while lsof /var/{{ item }}; do sleep 10; done;
      changed_when: false
      loop:
        - lib/dpkg/lock-frontend
        - lib/apt/lists/lock
        - cache/apt/archives/lock
      # Unattended upgrades can lock the dpkg lock file for long periods of time, so we timeout to skip the host and continue with the rest of the playbook
      timeout: 60

    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- name: Update apt
  hosts: docker_swarm_manager:docker_swarm_worker
  become: true
  tasks:
    - name: Wait for /var/lib/dpkg/lock-frontend to be released
      ansible.builtin.shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;
      changed_when: false

- name: Install NVIDIA driver
  hosts: docker_swarm_worker
  become: true
  roles:
    - role: centralesupelec.mydocker.gpu_pre_docker
      when: gpu_type is defined

- name: Install docker
  hosts: docker_swarm_manager:docker_swarm_worker
  become: true
  pre_tasks:
    - name: Register docker config for GPU
      when: gpu_type is defined
      ansible.builtin.set_fact:
        docker__daemon_json: "{{ gpu_pre_docker__daemon_json }}"
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
    # Install NVIDIA docker runtime after Docker to avoid installing docker-ce as a default APT dependency for the driver
    - role: centralesupelec.mydocker.gpu_post_docker
      when: gpu_type is defined

- name: Install ssh keys
  hosts: docker_swarm_worker:docker_swarm_manager
  tasks:
    - name: Provision ssh keys
      when: common_ssh_authorized_keys is defined
      ansible.posix.authorized_key:
        user: "{{ item.key }}"
        state: present
        key: "{{item.value | join('\n') if item.value is defined and item.value is iterable else ''}}"
        exclusive: true
      loop: "{{ (common_ssh_authorized_keys | default({})) | dict2items }}"
      tags:
        - ssh

- name: Create and configure docker swarm
  hosts: docker_swarm_manager:docker_swarm_worker
  roles:
    - centralesupelec.mydocker.ceph_install
    - role: centralesupelec.mydocker.docker_swarm
      vars:
        docker_swarm_volume_backend: "{{ enable_ceph | ternary('rbd', 'fs') }}"
  become: true

- name: Create and configure swap on workers
  hosts: docker_swarm_worker
  roles:
    - geerlingguy.swap
  become: true
