- name: Untaint servers that are actually active
  hosts: localhost
  strategy: linear
  roles:
    - centralesupelec.mydocker.retrieve_state
    - role: centralesupelec.mydocker.untaint_servers
      vars:
        terraform_state: "{{ retrieve_state_result }}"
