- name: Untaint servers that are actually active
  hosts: localhost
  strategy: linear
  roles:
    - retrieve_state
    - role: untaint_servers
      vars:
        terraform_state: "{{ retrieve_state_result }}"
