---
- name: register installed packages
  package_facts:

- name: register gpu
  shell: "nvidia-smi -L"
  register: nvidia_smi
  changed_when: False

- name: read docker daemon config
  slurp:
    src: /etc/docker/daemon.json
  register: docker_daemon_config

- name: read nvidia-container-runtime config
  slurp:
    src: /etc/nvidia-container-runtime/config.toml
  register: nvidia_container_runtime_config

- assert:
    that:
      - "'docker-ce' in ansible_facts.packages"
      - "'gpu=' in (docker_daemon_config.content|b64decode)"
    fail_msg: Docker must be configured

- assert:
    that:
      - "'nvidia-docker2' in ansible_facts.packages"
      - "'\\nswarm-resource' in (nvidia_container_runtime_config.content|b64decode)"
    fail_msg: nvidia-docker2 must be configured

- assert:
    that:
      - "'GPU 0' in nvidia_smi.stdout"
    fail_msg: Nvidia driver must be installed
